-- expression_condition
INSERT INTO expression_condition (id, create_time, update_time, code, name, description) VALUES (1, now(), now(), 'value', '值', null);
INSERT INTO expression_condition (id, create_time, update_time, code, name, description) VALUES (2, now(), now(), 'totalTimes', '总次数', null);
INSERT INTO expression_condition (id, create_time, update_time, code, name, description) VALUES (3, now(), now(), 'totalNumber', '总数', null);

-- expression_operator
INSERT INTO expression_operator (id, create_time, update_time, code, name, description) VALUES (1, now(), now(), '==', '等于', null);
INSERT INTO expression_operator (id, create_time, update_time, code, name, description) VALUES (2, now(), now(), '>', '大于', null);
INSERT INTO expression_operator (id, create_time, update_time, code, name, description) VALUES (3, now(), now(), '>=', '大于等于', null);
INSERT INTO expression_operator (id, create_time, update_time, code, name, description) VALUES (4, now(), now(), '<', '小于', null);
INSERT INTO expression_operator (id, create_time, update_time, code, name, description) VALUES (5, now(), now(), '<=', '小于等于', null);
INSERT INTO expression_operator (id, create_time, update_time, code, name, description) VALUES (6, now(), now(), '!=', '不等于', null);

-- event
INSERT INTO event (id, create_time, update_time, code, status, name, description) VALUES (1, now(), now(), 'daily_login', 1, '每日登录', null);
INSERT INTO event (id, create_time, update_time, code, status, name, description) VALUES (2, now(), now(), 'invite_friend', 1, '邀请用户', null);
INSERT INTO event (id, create_time, update_time, code, status, name, description) VALUES (3, now(), now(), 'daily_sign_in', 1, '每日签到', null);
INSERT INTO event (id, create_time, update_time, code, status, name, description) VALUES (4, now(), now(), 'share', 1, '分享', null);
INSERT INTO event (id, create_time, update_time, code, status, name, description) VALUES (5, now(), now(), 'buy_product', 1, '购买产品', null);
INSERT INTO event (id, create_time, update_time, code, status, name, description) VALUES (6, now(), now(), 'buy_vip', 1, '成为VIP', null);
INSERT INTO event (id, create_time, update_time, code, status, name, description) VALUES (7, now(), now(), 'pay', 1, '完成付费', null);
INSERT INTO event (id, create_time, update_time, code, status, name, description) VALUES (8, now(), now(), 'user_register', 1, '用户注册', null);

-- task
INSERT INTO task (id, create_time, update_time, status, name, description, type, sequence_weight, events, complete_rule, complete_limit_rule, complete_type, after_complete_type, after_complete_rule, complete_engage_way, complete_engage_rule, button_config, redirect_link_config) VALUES (1, now(), now(), 1, '每日登录', null, 1, 1, 'daily_login', '{"event":"daily_login","type":1,"condition":"value","operator":"==","value":"true","expression":"value == true"}', '{"type":1,"period":1,"times":1}', 2, 1, '{"id":1,"number":10}', 2, null, '{"text":{"0":"未完成","1":"领取奖励","2":"已完成"}}', '{}');
INSERT INTO task (id, create_time, update_time, status, name, description, type, sequence_weight, events, complete_rule, complete_limit_rule, complete_type, after_complete_type, after_complete_rule, complete_engage_way, complete_engage_rule, button_config, redirect_link_config) VALUES (2, now(), now(), 1, '邀请好友', null, 1, 1, 'invite_friend', '{"event":"invite_friend","type":1,"condition":"value","operator":"==","value":"true","expression":"value == true"}', '{"type":9}', 2, 1, '{"id":1,"number":20}', 2, null, '{"text":{"0":"未完成","1":"领取奖励","2":"已完成"}}', '{}');
INSERT INTO task (id, create_time, update_time, status, name, description, type, sequence_weight, events, complete_rule, complete_limit_rule, complete_type, after_complete_type, after_complete_rule, complete_engage_way, complete_engage_rule, button_config, redirect_link_config) VALUES (3, now(), now(), 1, '每日签到', null, 1, 1, 'daily_sign_in', '{"event":"daily_sign_in","type":1,"condition":"value","operator":"==","value":"true","expression":"value == true"}', '{"type":1,"period":1,"times":1}', 2, 1, '{"id":1,"number":10}', 2, null, '{"text":{"0":"未完成","1":"领取奖励","2":"已完成"}}', '{}');
INSERT INTO task (id, create_time, update_time, status, name, description, type, sequence_weight, events, complete_rule, complete_limit_rule, complete_type, after_complete_type, after_complete_rule, complete_engage_way, complete_engage_rule, button_config, redirect_link_config) VALUES (4, now(), now(), 1, '分享', null, 1, 1, 'share', '{"event":"share","type":1,"condition":"value","operator":"==","value":"true","expression":"value == true"}', '{"type":1,"period":1,"times":5}', 2, 1, '{"id":1,"number":10}', 2, null, '{"text":{"0":"未完成","1":"领取奖励","2":"已完成"}}', '{}');
INSERT INTO task (id, create_time, update_time, status, name, description, type, sequence_weight, events, complete_rule, complete_limit_rule, complete_type, after_complete_type, after_complete_rule, complete_engage_way, complete_engage_rule, button_config, redirect_link_config) VALUES (5, now(), now(), 1, '购买5次产品', null, 1, 1, 'buy_product', '{"event":"buy_product","type":1,"condition":"totalTimes","operator":">=","value":5,"expression":"totalTimes >= 5"}', '{"type":8}', 2, 1, '{"id":1,"number":100}', 2, null, '{"text":{"0":"未完成","1":"领取奖励","2":"已完成"}}', '{}');
INSERT INTO task (id, create_time, update_time, status, name, description, type, sequence_weight, events, complete_rule, complete_limit_rule, complete_type, after_complete_type, after_complete_rule, complete_engage_way, complete_engage_rule, button_config, redirect_link_config) VALUES (6, now(), now(), 1, '成为会员', null, 1, 1, 'buy_vip', '{"event":"buy_vip","type":1,"condition":"value","operator":"==","value":"true","expression":"value == true"}', '{"type":8}', 2, 1, '{"id":1,"number":100}', 2, null, '{"text":{"0":"未完成","1":"领取奖励","2":"已完成"}}', '{}');
INSERT INTO task (id, create_time, update_time, status, name, description, type, sequence_weight, events, complete_rule, complete_limit_rule, complete_type, after_complete_type, after_complete_rule, complete_engage_way, complete_engage_rule, button_config, redirect_link_config) VALUES (7, now(), now(), 1, '首次完成付费', null, 1, 1, 'pay', '{"event":"pay","type":1,"condition":"totalTimes","operator":"==","value":1,"expression":"totalTimes == 1"}', '{"type":8}', 2, 1, '{"id":1,"number":200}', 2, null, '{"text":{"0":"未完成","1":"领取奖励","2":"已完成"}}', '{}');
INSERT INTO task (id, create_time, update_time, status, name, description, type, sequence_weight, events, complete_rule, complete_limit_rule, complete_type, after_complete_type, after_complete_rule, complete_engage_way, complete_engage_rule, button_config, redirect_link_config) VALUES (8, now(), now(), 1, '注册', null, 1, 1, 'user_register', '{"event":"user_register","type":1,"condition":"value","operator":"==","value":"true","expression":"value == true"}', '{"type":8}', 2, 1, '{"id":1,"number":200}', 2, null, '{"text":{"0":"未完成","1":"领取奖励","2":"已完成"}}', '{}');